In [248]:
import sklearn 
import csv
import numpy as np 
import math
import matplotlib.pyplot as plt
import copy
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

In [249]:
with open('wine_train.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)

#print(np.shape(data))

data_array = np.asarray(data, dtype=np.float32)
data_unnorm = copy.deepcopy(data_array)

data_fea_unnorm = data_unnorm[:,0:13]
print(np.shape(data_fea_unnorm))
mean_unnorm = np.mean(data_fea_unnorm, axis = 0)
std_unnorm = np.std(data_fea_unnorm, axis = 0)
print(np.shape(mean_unnorm))
print("mean of unnormalized data points is: ") 
print(mean_unnorm)
print("standard deviation of unnormalized data points is: ") 
print(std_unnorm)

data_fea_norm = copy.deepcopy(data_fea_unnorm)
sc_X = StandardScaler()
sc_X.fit(data_fea_norm)  #the normalizing factors should be calculated from the training data only
data_fea_norm = sc_X.transform(data_fea_norm)     #	Fit to data, then transform it.
print('After standardization:') 
print(data_fea_norm)
#print(np.shape(data_fea_norm))

(89, 13)
(13,)
mean of unnormalized data points is: 
[1.2965391e+01 2.2699997e+00 2.3762920e+00 1.9649437e+01 9.8910110e+01
 2.2723591e+00 2.0294383e+00 3.6067417e-01 1.5761796e+00 5.0912361e+00
 9.5321345e-01 2.5603375e+00 7.2970789e+02]
standard deviation of unnormalized data points is: 
[8.1956011e-01 1.1030642e+00 2.7300403e-01 3.4651763e+00 1.1558973e+01
 6.1454839e-01 9.1971827e-01 1.2024129e-01 5.4147017e-01 2.4043779e+00
 2.2990756e-01 7.2346151e-01 3.0722125e+02]
After standardization:
[[ 0.957351   -0.48954538  0.12347054 ...  0.85593736  0.46949705
   1.9213911 ]
 [ 0.28625914 -0.44421718 -0.86552584 ...  0.4209799   1.1606189
   1.0425457 ]
 [ 0.12763734 -0.69805545 -1.0120445  ...  0.9864245   0.17922582
   0.94489616]
 ...
 [-0.5312526   2.9372725   0.965949   ... -0.57942194 -1.2030177
  -0.6988706 ]
 [-0.10419382  0.65272725  0.08684108 ... -0.9273878  -1.5762236
  -0.6500458 ]
 [ 0.93294716  1.8947222  -0.42597228 ... -0.753405   -1.1200832
  -0.6825957 ]]


In [250]:
#take first tow columns
feature_2 = data_fea_norm[:,0:2]
print(np.shape(feature_2))
class_labels = data_unnorm[:,13]
print(np.shape(class_labels))
#print(class_labels)

(89, 2)
(89,)


In [251]:
def calcul_accuracy(real_label, pre_label):
    cnt = 0
    for i in range(len(real_label)):
        if real_label[i] == pre_label[i]:
            cnt += 1
    return cnt/len(real_label)

#perceptron on the first two features
perceptron = Perceptron(max_iter=1000, tol=0.0001, random_state = None) 
perceptron.fit(feature_2, class_labels) #fit(X, y[, coef_init, intercept_init, ...])	Fit linear model with Stochastic Gradient Descent. 
print("feature_2's final Weight:")
#print(perceptron.intercept_)             #不懂
final_wei1 = perceptron.coef_
print(final_wei1)

label_train_pred1 = perceptron.predict(feature_2)      #Predict class labels for samples in X.
#print(label_train_pred1)
mean_ar = perceptron.score(feature_2, class_labels)
#print(mean_ar)
mean_accuracy1 = calcul_accuracy(class_labels, label_train_pred1)    #Returns the mean accuracy on the given test data and labels.
print("mean accuracy is " + str(mean_accuracy1))

#print(calcul_accuracy(label_train_pred1, class_labels))

feature_2's final Weight:
[[ 2.56236516 -0.78871346]
 [-2.80638263 -2.11229876]
 [ 1.37876909  1.5411631 ]]
mean accuracy is 0.797752808988764


In [252]:
###all features
perceptron.fit(data_fea_norm, class_labels)
print("feature_all's final Weight:")

final_wei2 = perceptron.coef_
print(final_wei2)
label_train_pred2 = perceptron.predict(data_fea_norm)      #Predict class labels for samples in X.
#print(label_train_pred2)
mean_accuracy2 = calcul_accuracy(label_train_pred2, class_labels)
print("mean accuracy is " + str(mean_accuracy2))
#mean_ar2 = perceptron.score(data_fea_norm, class_labels)
print(mean_ar2)

feature_all's final Weight:
[[ 2.96788298  1.57742418  4.31404927 -2.77139503  1.94313723 -1.21364307
   3.35605998 -2.71084106 -0.61484706 -1.09075367  3.30254799  2.40789942
   6.29594261]
 [-4.8899878  -3.97982317 -3.19499743  2.16342021 -2.12296724 -1.76689468
  -0.85175116  1.69696185  0.770271   -7.80350854  2.41523474 -0.19071857
  -5.76702636]
 [ 2.23578269  1.54116194  2.62909292  0.51848108  2.63524008 -1.44145373
  -3.82005122 -2.37817672 -2.31392536  4.6986853  -4.59627768 -2.65111257
  -0.73482172]]
mean accuracy is 1.0
1.0


In [253]:
###test set
with open('wine_test.csv', newline='') as f:
    reader_t = csv.reader(f)
    data_t = list(reader_t)

data_array_t = np.asarray(data_t, dtype=np.float32)
data_unnorm_t = copy.deepcopy(data_array_t)

data_fea_unnorm_t = data_unnorm_t[:,0:13]
print(np.shape(data_fea_unnorm_t))

data_fea_norm_t = copy.deepcopy(data_fea_unnorm_t)

data_fea_norm_t = sc_X.transform(data_fea_norm_t)     #	Fit to data, then transform it using 
print('After standardization:') 
print(data_fea_norm_t)
print(np.shape(data_fea_norm_t))

(89, 13)
After standardization:
[[ 1.5308298   1.5592928   0.48976514 ... -0.2749518   1.3403103
   0.0986004 ]
 [-1.1779407  -1.2238635  -1.3783392  ...  1.8563395   0.7735903
  -1.4703016 ]
 [ 0.8597378  -0.92469686 -1.6713753  ...  1.2039034  -0.13869023
  -0.32454744]
 ...
 [-0.60446197 -0.6799242  -0.6457491  ...  0.8994331   0.09629128
   0.67473245]
 [ 0.79872924  2.4295955  -0.09630711 ... -0.18796012 -0.7054102
  -0.58494616]
 [-0.6288659   0.6889898   0.965949   ... -1.2318579  -1.1477281
   0.4891984 ]]
(89, 13)


In [254]:
#take first tow columns
feature_2_t = data_fea_norm_t[:,0:2]
print(np.shape(feature_2_t))
class_labels_t = data_unnorm_t[:,13]
print(np.shape(class_labels_t))
#print(class_labels_t)

perceptron_t = Perceptron(max_iter=1000, tol=0.0001, random_state = None) 
#use weight in training data as starting weight
perceptron_t.fit(feature_2_t, class_labels_t, coef_init = final_wei1)      
print("feature_2_t's final Weight:")
print(perceptron_t.coef_)

label_train_pred1_t = perceptron_t.predict(feature_2_t)      #Predict class labels for samples in X.
#print(label_train_pred1_t)

mean_accuracy1_t = perceptron_t.score(feature_2_t, class_labels_t)    #Returns the mean accuracy on the given test data and labels.
print("mean accuracy is " + str(mean_accuracy1_t))
mean_ac3 = calcul_accuracy(label_train_pred1_t, class_labels_t)
#print(calcul_accuracy(label_train_pred1_t, class_labels_t))
#print(mean_ac3)

(89, 2)
(89,)
feature_2_t's final Weight:
[[ 2.37373081 -1.36891671]
 [-2.06208771  0.60739965]
 [ 0.70203731  0.90656301]]
mean accuracy is 0.7078651685393258


In [255]:
#all_features_test = data_fea_norm_t[:,0:13]

###all features for test
perceptron_t.fit(data_fea_norm_t, class_labels_t, coef_init = final_wei2)
print("feature_all's final Weight:")
print(perceptron_t.coef_)
label_train_pred2_t = perceptron_t.predict(data_fea_norm_t)      #Predict class labels for samples in X.
#print(label_train_pred2_t)
mean_accuracy2_t = perceptron_t.score(data_fea_norm_t, class_labels_t)
print("mean accuracy is " + str(mean_accuracy2_t))
mean_ac3 = calcul_accuracy(label_train_pred2_t, class_labels_t)
print(mean_ac3)
print('interation times: ')
print(perceptron_t.n_iter_)

feature_all's final Weight:
[[ 4.47718757  0.47141428  1.02274498 -6.91340923 -0.7776438  -1.32462251
   2.49404704 -1.01948577 -0.20688564 -0.25636744 -0.02023274  0.4750878
   6.29118815]
 [-6.28001904 -5.21275248 -4.24778601  3.83689271 -0.84082723 -0.03437197
   4.3333978  -0.20464438  2.17821469 -6.68368795  2.79115524  0.23870879
  -7.85211759]
 [ 4.03230448 -0.01813136  4.34244732  4.0959706  -1.73706185 -1.36960012
  -5.56337938  0.23361239 -0.4909647   6.4652195  -4.0774564  -3.14592427
  -0.48663856]]
mean accuracy is 1.0
1.0
interation times: 
9


In [256]:
#d
epoch = 100
Weight1 = np.zeros((3,2)) 
accu_tmp1 = 0
#perceptron1 = Perceptron(max_iter=1000, tol=0.0001, random_state = None)   
for i in range(epoch):   
    perceptron1 = Perceptron(max_iter=1000, tol=0.0001, random_state = None)   
    random_w1 = np.random.randn(3,2)
    perceptron1.fit(feature_2, class_labels, coef_init = random_w1)
    label1_train_pred = perceptron1.predict(feature_2) 
    acc_train1 = perceptron1.score(feature_2, class_labels) 
    if(acc_train1 > accu_tmp1):
        accu_tmp1 = acc_train1 
        Weight1 = perceptron1.coef_ 
        #ini_weight1 = random_w1      
"""
    random_w2 = np.random.randn(3,13)
    perceptron1.fit(data_fea_norm, class_labels, coef_init = random_w2)
    label2_train_pred = perceptron1.predict(data_fea_norm) 
    acc_train2 = perceptron1.score(data_fea_norm, class_labels) 
    if(acc_train2 > accu_tmp2):
        accu_tmp2 = acc_train2 
        Weight2 = perceptron1.coef_
        ini_weight2 = random_w2          
"""                       
print(Weight1)
print(accu_tmp1)
print(perceptron1.n_iter_)
#print(Weight2)       #two are the same
#print(accu_tmp2)
""" 
    perceptron1.fit(feature_2, class_labels, coef_init = random_w)
    label1_train_pred = perceptron1.predict(feature_2) 
    acc_train1 = perceptron1.score(feature_2, class_labels) 
    if(acc_train1 > accu_tmp1):
        accu_tmp1 = acc_train1 
        Weight1 = perceptron1.coef_ 
        ini_weight1 = random_w
"""      
    

[[ 2.66895051 -0.88679077]
 [-3.56210582 -2.02978359]
 [ 0.3848902   0.80094763]]
0.8426966292134831
10


' \n    perceptron1.fit(feature_2, class_labels, coef_init = random_w)\n    label1_train_pred = perceptron1.predict(feature_2) \n    acc_train1 = perceptron1.score(feature_2, class_labels) \n    if(acc_train1 > accu_tmp1):\n        accu_tmp1 = acc_train1 \n        Weight1 = perceptron1.coef_ \n        ini_weight1 = random_w\n'

In [257]:
perceptron1.fit(feature_2_t, class_labels_t, coef_init=Weight1)    #use best training initiate weight

test_label1 = perceptron1.predict(feature_2_t) 
acc_test1 = perceptron1.score(feature_2_t, class_labels_t) 
print(acc_test1)

print(Weight1)
print(perceptron1.coef_)
#print(perceptron1.n_iter_)

"""
perceptron1.fit(data_fea_norm_t, class_labels_t, coef_init = ini_weight2)    #use best training initiate weight
test_label2 = perceptron1.predict(data_fea_norm_t) 
acc_test2 = perceptron1.score(data_fea_norm_t, class_labels_t) 
print(acc_test2)
print(perceptron1.coef_)
"""

0.7191011235955056
[[ 1.56519354 -1.15876042]
 [-1.78066846 -0.40702914]
 [ 1.20334998  1.71657481]]
[[ 1.56519354 -1.15876042]
 [-1.78066846 -0.40702914]
 [ 1.20334998  1.71657481]]


'\nperceptron1.fit(data_fea_norm_t, class_labels_t, coef_init = ini_weight2)    #use best training initiate weight\ntest_label2 = perceptron1.predict(data_fea_norm_t) \nacc_test2 = perceptron1.score(data_fea_norm_t, class_labels_t) \nprint(acc_test2)\nprint(perceptron1.coef_)\n'

In [258]:
Weight2 = np.zeros((3,13))
#ini_weight2 = np.zeros((3,13))
accu_tmp2 = 0
perceptron2 = Perceptron(max_iter=1000, tol=0.0001, random_state = None)     ##????为什么放进循环  
for i in range(100): 
    
    random_w2 = np.random.randn(3,13)
    perceptron2.fit(data_fea_norm, class_labels, coef_init = random_w2)
    label2_train_pred = perceptron2.predict(data_fea_norm) 
    acc_train2 = perceptron2.score(data_fea_norm, class_labels) 
    if(acc_train2 > accu_tmp2):
        accu_tmp2 = acc_train2 
        Weight2 = perceptron2.coef_
    
print('all features weight is ' + str(Weight2))
print('accuracy for training data is ' + str(accu_tmp2))

perceptron2.fit(all_features_test, class_labels_t, coef_init = Weight2)    #use best training initiate weight
test_label2 = perceptron2.predict(data_fea_norm_t) 
acc_test2 = perceptron2.score(data_fea_norm_t, class_labels_t) 
print(acc_test2)
print(perceptron2.coef_)

all features weight is [[ 1.01030482  1.54174978  2.77978482 -1.55356436  0.57699227  0.04844588
   3.4095022  -0.94332465  1.08950633  0.2755902   1.05142774  1.62093587
   5.22989665]
 [-6.51245126 -5.34977134 -3.07745092  3.42743264 -1.74338091  0.84682193
   1.5153428   4.37073861  0.30830707 -9.70154192  0.92117845 -0.03401687
  -8.34531583]
 [ 1.99192419  0.71000519  1.78091195  0.58691982 -0.78281875 -1.16437171
  -1.83762887 -1.86581723 -2.63176456  6.75446012 -4.33757414 -1.6259074
  -1.0461937 ]]
accuracy for training data is 1.0
1.0
[[ 5.04307009  0.8263439   2.56145945 -3.58962026 -1.0203604   0.30702461
   1.58867804 -0.4027867   1.7695967  -0.82391448  1.20664478  0.66082896
   6.05001039]
 [-5.67367783 -5.47156187 -4.59792646  3.55384765 -1.32611607  1.4938021
   4.28543857  1.67332319  2.99636363 -9.10341701  1.97685196  1.48432944
  -8.14080565]
 [ 4.32432391  0.81605765  1.5149818   3.50434864 -1.93695515 -2.4682778
  -5.17082157 -0.52633802  0.69355963  8.5851582  -1